### ISSUE TITLE
Delete a video with ziggeo v2

### ISSUE THREAD

**Issue by zyph00** [Ziggeo/ziggeo-client-sdk#11]
Hey guy's

I need you an another time.. How can I delete a video with ziggeo v2?

With reverse engineering I found that function:

`ziggeoApp.videos.destroy(a, b, c);`

But I don't know what params the function needs. Is it possible to delete a video by the videoToken?

**Comment by Bane-D** [comment]
Hi,

Yes, that is the right call. It would be removed by providing the token in the function.

The call would look like so:
```
ziggeoApp.videos.destroy( videoToken ).success(
	function(result) {
		//result is object
		console.log(result);
	}
);
```
It is good to mention that by default we do not allow the JS SDK to be able to delete the video without enabling this in the dashboard (since anyone could do it then).

Alternatively you would have auth token that allows this specific action to be made.

If you would use single auth token for this, like one created through dashboard (server side auth token), it would not be recommended for public website. Possibly just for yourself in administration. For public facing websites you would be better off with client side auth tokens.

The client side auth tokens are generated by server side SDK, in which case it would be easier to remove them from within the server side SDK (which do not require auth tokens) :)

You can see auth tokens here: https://ziggeo.com/docs/sdks/server-side/

Hope this helps :)

Regards,
Bane

**Comment by zyph00** [comment]
Thank you very much for your answer!

Regards,
Thomas
