### ISSUE TITLE
Requests still to embed.ziggeo.com/v1/* instead of v2

### ISSUE THREAD

**Issue by zyph00** [Ziggeo/ziggeo-client-sdk#14]
Hey guy's

Exceptionally it's more a question than a problem.

I saw in the network console of my browser that Ziggeo makes a request to: `embed.ziggeo.com/v1/applications/{TOKEN}/session`

And I'm wondering why still *v1* and not *v2* because I'm using v2 of Ziggeo.

And the other question is: We are fetching the images of the video over this url: `embed.ziggeo.com/v1/applications/{TOKEN}/videos/{VIDEO}/image` and I'm now a little bit scared that the url changes from v1 to v2 and it's not working anymore.

Regards,
Thomas

**Comment by Bane-D** [comment]
Hi Thomas,

Good questions :)

Short answer is that there is no need to worry about it.

Longer answer:

We like to keep our system modular as much as possible. That way we can change one part or sub-system without really affecting all the rest.

With that said, our v1 and v2 that are referencing are JS versions - or versions of our JS based system. The URL endpoints are using our API instead.

Now when we started we set the API to use v1, to make it easier in future if we decided at any point to introduce a different version (ie v2, etc) and this makes it super easy for us.

Of course this can introduce a confusion since you can not really see if that should be like that or not.

So the difference between v1 and v2 in the JS SDK is that v1 is older, and when it was created Flash was practically the only way of recording. It was made to be solid and well rounded. As things evolve, our v1 would either need a whole rewamp or a new subsystem to be created, hence v2.

Both of them however are contacting our API v1 that is in use, and will likely be in use for quite some time as we are still actively developing it. At some later time of course if there is a decision to have v2 of the server side API, then this would be available, however v1 would still work (just as we do with v1 of JS SDK).

Hope this makes sense :)

Regards,
Bane

**Comment by zyph00** [comment]
Hey Bane

Thank you for the answer! This makes sense for me!

Regards,
Thomas
