### ISSUE TITLE
Parameter 'force_refresh' overwrites max video length

### ISSUE THREAD

**Issue by zyph00** [Ziggeo/ziggeo-client-sdk#15]
Hey guy's

Found an another problem.

I have an upload for videos with a maximum length of 120 seconds set with the `timelimit` attribute.

So now if I upload a video which is over 120 seconds long and then start to play it the player shows the full video and not only the maximum 120 seconds. So I inspected the url and found out that the player adds a parameter called 'force_refresh=false' to the video url. If I remove this parameter the video contains the correct length of 120 seconds.

So is this a bug of for what is that parameter? Is it possible to remove it?

Regards,
Thomas

**Comment by Bane-D** [comment]
Hi Thomas,

Thank you for reporting it. It is actually not an issue. If I understood you correctly, you are experiencing this only with the uploads, not with the recordings.

What is happening is that while recording we can see the info about the length it has, size, etc..

For the videos that are being uploaded we do not have access to the actual video length and maybe even size. That is why we will crop / cut it on our server side.

Because of it, it could happen that the video that is played back to you right away is longer, however the final video (video others would see) would definitely be cropped to right size.

It is also possible that some form of caching is at play as well, and that parameter you mentioned is basically just there for the flush from cache if needed, nothing else :)

Hope this explains what is happening.

Regards,
Bane

**Comment by zyph00** [comment]
Hey Bane

Ok, thank you for the information.

My problem is that when I upload a video with a limit and then play it with the player the video is unlimited. But on the admin panel of ziggeo the video is limited. And so I dont know how to get the limited version of the video.

Regards,
Thomas

**Comment by Bane-D** [comment]
Hi Thomas,

I see. For that, it might actually be helpful to create a new video player instead of using the player that starts off from the recorder.

That way any data that it has cached will be dropped and it will play the default video stream instead.

You could do this by waiting for `ready_to_play` event for example (best in this case), or `verified` if you prefer and then create a new player with the video.

Just example:
```
<link rel="stylesheet" href="https://assets-cdn.ziggeo.com/v2-stable/ziggeo.css" />
<script src="https://assets-cdn.ziggeo.com/v2-stable/ziggeo.js"></script>
<script>
	var ziggeo_app = new ZiggeoApi.V2.Application({
		token:"APPLICATION_TOKEN"
	});
	
	ziggeo_app.on("ready", function (  ) {
		//set up recorder
		var recorder = new ZiggeoApi.V2.Recorder({
			element: document.getElementById("ziggeo-recorder-placeholder"),
			attrs: {
				width: 640,
				height: 480,
				theme: "modern",
				themecolor: "red"
			}
		});

		//we activate the recorder
		recorder.activate();

		//we set up the `ready_to_play` event..
		recorder.on('ready_to_play', function() {
			//set up the player
			var player = new ZiggeoApi.V2.Player({
				element: document.getElementById("ziggeo-player-placeholder"),
				attrs: {
					width: 640,
					height: 480,
					theme: "modern",
					themecolor: "red",
					video: recorder.get('video')
				}
			});

			player.activate();
			//just to remove the recorder since we do not need it, we could of course
			// .hide() it instead
			recorder.destroy();
		});
	});
</script>
...
<div id="ziggeo-recorder-placeholder"></div>
<div id="ziggeo-player-placeholder"></div>
```

Hope the example explains what I mean.

Regards,
Bane

**Comment by zyph00** [comment]
Hey Bane

Cool, thank you for the code snippet.

Just another question. Is it possible to deactivate the other streams to just use one? At the moment I've got an 'hd' and a '360' stream. I just want one. Where can I configure this?

Regards,
Thomas

**Comment by Bane-D** [comment]
Hi,

You are welcome Thomas, hope it helped :)

In regards to the streams, you can actually easily configure this through video profiles (please note that this requires specific plan to be available): https://ziggeo.com/pricing

My personal opinion is that you can keep them both since we do not really charge for additional streams - one of the benefits of using Ziggeo for hosting.

Also it makes it easy to use any stream for playback and later this year it could be useful with adaptive streaming (for your end users that have slower connection for example).

Of course, now to removal process.

1. You could use our server side SDKs
* benefit: you could just specify the stream you want to remove from some video and that is it, all is done for you, no other codding needed
* possible downside: you need to setup the environment if not already using any. Seeing how we have a lot of server side SDKs and that most people also use some form of server side programming this is very easy to be added.

2. You could use our JS API call
* same end result as the Server side API, however you need to have some auth tokens set up or created to make this request, or if done in the back, you could use the ones created from the dashboard

3. setting up the video profiles to create only the profiles you are interested in
* This way you would end up with original stream and the default or few other streams per your own setup (SD or HD).

The easiest would definitely be the 3rd option since you would just set it all once and then you can use the key or token reference of the video profile to tell our servers what you want to happen in the back.

To set them up, you would:
1. log into your Ziggeo account
2. go to the application that you want to use
3. go to the Manage page of that application
4. click on the Video Profiles section
5. set up the video profiles.

To set them up you would:
1. fill out the box for key if you want to reference the video profile with key, or leave it blank for our auto generated token (I think that tokens are better since they do not tell what the video profile is for to end user, while key does)
2. fill in the label that you want to associate with the key or token. This is basically to allow you to easily distinguish the profiles within the dashboard. This info is only seen by you and to whom you give your details
3. click on plus button
4. now in the list bellow you will have the new video profile created and we need to edit it (to add processes) so click on the button with the pen to the right of the entry
5. Scroll a bit down to edit the video profile (all of the info entered here is shown only to you).

Things to note:
* There can only be 1 default stream.
* checking `custom` checkbox allows you to enter custom values, we recommend them being dividable by 4, since that is best for video processing (in general).
* Expert settings allow you to control what happens if video is smaller or larger than the resolution that you got in, so this can be useful at times

Hope this helps :)

Regards,
Bane
