### ISSUE TITLE
access recorded video from JS

### ISSUE THREAD

**Issue by Ali-Dalal** [Ziggeo/ziggeo-client-sdk#19]
Is there any way to access the recorded video using JS as a binary file?

**Comment by ibnutri** [comment]
Hi @Ali-Dalal 

Could you explain more about "using JS as binary file" 
Or can you explain about what you want to do in which platform?

**Comment by Ali-Dalal** [comment]
Hi Ibnutri,

I am creating a JS library to help developers record video from the browser.

https://github.com/Ali-Dalal/easy-recorder-js

The problem is this library can't be used with Safari and Edge due to MediaRecord API limitation.

The library allows the users to get the recorded video as a blob object.

The library is an extra layer over RecordRTC to make the API easier to use.

So, I just wanted to check if the video is recorded using Flash, is it possible to get the blob of the recorded data?

Thanks.

**Comment by Ali-Dalal** [comment]
Hi Ibnutri,

I am creating a library to record video from the browser.

https://github.com/Ali-Dalal/easy-recorder-js

The library is an extra layer over RecordRTC to make the API easier with more events.

So, Any way to record the video from Safari/Edge and access the recorded video as a blob object so the video can be downloaded to hard disk?

MediaRecord API doesn't support Safari and Edge so the library can't be used with those browsers

Thanks.

**Comment by ibnutri** [comment]
Hi @Ali-Dalal 

As far as I know, Safari, edge, and IE don't have this feature implemented. So you would need Flash to do this for you. I think it's not Javascript's weakness. But more like the platform's (in this case browser) limitation.

**Comment by Ali-Dalal** [comment]
Hi @ibnutri 

Any suggestions for open source flash libraries that can be used to record video from Safari/Edge?

I appreciate your help.

Thanks

**Comment by ibnutri** [comment]
Hi @Ali-Dalal 

In regards to Flash, there is, unfortunately, no way to generate a BLOB as you are asking
even if there would be, the main problem would be that the BLOB mass data would reside within the Flash environment, and copying/moving it over to the JS environment where he probably would like to have access to the BLOB is not really possible / super slow, because the methods of moving data between Flash and JS are geared towards very small chunks of data, not mass data.

If you are interested in accessing the "raw" camera, I can only suggest BetaJS framework. You could use betajs-media and if you need the raw camera access, and betajs-media-components if you need UI on top of that. 

We at Ziggeo are using it in the back as well. Of course, I do want to mention that if you ever decide to just use some library that handles everything for you, you can check our Ziggeo library. It does require subscription however it extends the BetaJS framework in some areas so you can just relax and utilize it in your projects.

Of course, if you still prefer the DIY approach, BetaJS is definitely the one to check.

You could check betajs at https://github.com/betajs

**Comment by Ali-Dalal** [comment]
Hi @ibnutri 

Many thanks,
