### ISSUE TITLE
Confusing versioning

### ISSUE THREAD

**Issue by ghost** [Ziggeo/ziggeo-client-sdk#20]
I don't get the versioning system of ziggeo client sdk. 
Looks like there is a map between client sdk and Ziggeo api version?

At the time of this writing the `head tag generator` gives me 
https://assets.ziggeo.com/v2-stable/ziggeo.js
for the latest stable version, which makes me believe `v0.0.30 ` is the last stable version, but I cannot find any `v2.30.0`.

Currently I'm using `v2.33.2` which I know by inspecting console that's is a prerelease version.

How can I easily figure the mapping between them and get the latest stable version through npm registry?

**Comment by Bane-D** [comment]
Hi Francisco,

We have decided recently to change the versioning of our SDKs which is why it seems off at this time.

We have v1 and v2 versions of our system, both however were bundled as 0.X.Y. Now to make it easier to understand what is actually being used we now have the versioning just as you mentioned (v2.33.2).

You can see this happened with the release of r31, so for stable (currently r30) revision:
https://assets.ziggeo.com/v2-r30/ziggeo.js
you are shown 0.30

On the other hand for revision r31:
https://assets.ziggeo.com/v2-r31/ziggeo.js
you are shown 2.31.2

In general we are still making few changes to the versioning just to make it better for everyone across all of our SDKs (which is why v1.X.Y does not show as v1, rather as v2).

Now in terms of the revisions, we are actively moving the stable revision. You can see them here: https://ziggeo.com/docs/sdks/javascript/version-history if you want to manually pick a specific version as well as to see what each brings.

In terms of  seeing which version is stable, that is not yet possible, however I see that we will have a flag that will help with the same. So there will be a flag for all new stable revisions stating which one is (or was) considered as stable revision.

For now, please do feel free to use the link above to check which revision you prefer to grab (I suggest stable or higher). Of course in the dev preview version (such as currently r33) it is possible that new changes are pushed at any time.

Regards,
Bane

**Comment by ghost** [comment]
Got it! Thanks 👍
