### ISSUE TITLE
Meaning of events upload, verified and processed

### ISSUE THREAD

**Issue by clluiz** [Ziggeo/ziggeo-client-sdk#22]
Whats the difference between this events? What is done in each one?

**Comment by Bane-D** [comment]
Hi Cleiton,

The upload, verified and processed [events](https://ziggeo.com/docs/sdks/javascript/browser-interaction/events) happen in the exact order that you had mentioned them.

The exact function of each is to tell you which stage is currently happening. For example regardless if it is video, screen or audio recording, what follows is always the uploading first. Uploading starts, progresses and then finishes.

Before uploading starts and during its life, the recorder code must not be changed. If DOM is changed in a way that corrupts the embedding structure, or if you use any of our methods such as `.reset()` or `.destroy()` the data will be destroyed as well and the upload stopped.

Once the uploading event finishes the file is on our servers. At that point in time you can do anything you want with the embedding on the page. You can even go to different page if you want.

Still we do recommend waiting for _verification_ event to fire. Now the verification event is something of our making. Basically our servers utilize a special algorithm to check the uploaded data quickly if it can be processed. Most of the time all videos will be processed, however if someone is on bad connection that by some chance results in corrupt data being uploaded or they send a bad file (file upload), the system will reject it and show a message.
The example of this would be that someone uploads a pdf instead of mp4 file.

This process is added so that you do not wait for entire processing to happen to see if it worked or failed. Once verification passes you can be sure that data we received is looking good and that you can do anything you want to / with embedding and with your end-user workflow.

Now the processing event is the last one. It is actually letting you know the stages of processing on our servers. The processing time itself will always take more than verification event would, so it is not needed to wait for this to finalize. You of course can if that is your preferred workflow. Once it fires, you can be sure that video is available for playback to everyone.

With this bit of info, lets see how they are used.

Most common setup is just to listen for verification event and then base the rest of the workflow once it fires.

The upload events are usually used when you want to create your custom progress bar. Some of our customers like to do this, making our system even more off the native element of their pages.

The progress events are often used for progress bar, however also in cases where it is important for you to know that the video was processed before going forward. In general we recommend the verified event as that is enough, and faster since you remove the wait for processing to fire.
Alternative to progress events are also our [webhooks](https://ziggeo.com/docs/api/webhooks/) and that is how it is most commonly checked for the progress events.

Hope this helps :)

Regards,
Bane

**Comment by Hamdan85** [comment]
for god's sake, why rerecord aren't triggered when redo button is clicked... 
which event is triggered just when you click stop (before image select)... 
why you guys just dont make you documentation clearer? Everyone that I know that uses you guys complain about this...

**Comment by Bane-D** [comment]
Hi Gabriel,

Have you checked out our documentation?

Events: https://ziggeo.com/docs/sdks/javascript/browser-interaction/events

Next to that one there are other pages that explain other aspects of our system that will make it easy to handle different operations of the same :)

If you have any other questions of course, happy to provide additional details, I would however like to ask you to open a different thread here to make it easier as it is not exactly the same as the original question.

PS: You can actually use two events to be aware of recording, starting with the rerecording one:
```
recorder.on("rerecord", function () {
    //Fires only when you re-record the video
});
recorder.on("recording", function () {
    //Fires any time recording starts, regardless if it is first recording or re-recording
});
```
Please do keep in mind that while we support all of our revisions different parameters and events are added in different revisions. So you need to switch the docs to the one you are using to find the ones available for it. By default it will show you everything from our auto updating revision tagged as "stable". The `rerecording` event for example is available in revision 34 and up while currently the stable tag points to revision 33.

Hope this helps,
Bane

**Comment by Hamdan85** [comment]
Of course I've checked the documentation.. I even have opened a ticket
already.

Rerecord aren't being triggered by rerecord on buttons from player or the
redo button after the process is finished (after upload)

And..

I didn't asked if it's recording... I asked about the event when we FINISH
recording... Today I need to use uploading event but when user needs to
choose a thumbnail image it gets delayed...

Thanks in advance

**Comment by ntshcalleia** [comment]
Hi Gabriel,

I think my colleague Bane mentioned the `recording` event to let you know that this is triggered as soon as recording starts - even when it’s a rerecording -, so this could be used as a way to know if and when the user has started rerecording.

For example, you could keep track of how many times `recording` has been triggered. If was more than once then you know the video is being re-recorded.

This is how you can listen to recorder events:

https://gist.github.com/ntshcalleia/ced744ed2a39d530cdbe9df17010972d

If you add your application token and try to re-record a video you'll see that the rerecord event is triggered right after you confirm the request.

To know when the user finished recording the event you're looking for is `recording_stopped`. This was missing from our documentation, so thank you for calling our attention to this issue. We'll be updating the docs to include this event.

**Comment by Hamdan85** [comment]
Guys, are you kidding me?
I have already said 4 times that I need to know when the recording STOPS...
not when start upload, not when it starts recording, not when it starts
being verified... WHEN IT STOPS.
Please... don't do this... I'm your customer... don't treat me like that.

I have already read the documentation many times... I know how to implement
triggers (which I'm already doing)... I want to know why rerecord isn't
triggered when you guys says it would.

Please, address my questions instead of divagating around. This is becoming
absurd.

Em sáb., 4 de abr. de 2020 às 13:03, Natasha Rocha <notifications@github.com>
escreveu:

**Comment by ntshcalleia** [comment]
Gabriel, if you read my message you'll see that I gave you the exact event you need to listen to so you know when recording stops. Again, the event you're looking for is `recording_stopped`.

**Comment by ntshcalleia** [comment]
If you check the example I sent you'll see that `rerecord` is indeed being triggered. If it's not being triggered with your own code, please send it to our support team so we can have a better understanding of what is happening.

**Comment by Hamdan85** [comment]
Natasha, that's EXACTLY what I'm doing... arent you from ziggeo's support?
I insist: set up a rerecord listener, record a video, select an image, wait
for it to upload and finish and click redo and notice that the event doesnt
trigger...

If youu arent from ziggeo's support, please forward it for someone that is
because I'm just opening a ticket on your support.

And, my question about the event triggered when recording STOPS remains
unaswered.

Em dom., 5 de abr. de 2020 às 09:24, Natasha Rocha <notifications@github.com>
escreveu:

**Comment by Bane-D** [comment]
Hi Gabriel,

We are trying to help you with your setup however it seems that there keeps to be a miscommunication happening making it impossible for my colleagues and myself to help you.

Please feel free to send us the code you are using to test out. We will then help sort out anything within your code that keeps it from happening since it works fine for us.

> And, my question about the event triggered when recording STOPS remains
unaswered.

Here is the last reply on this from my colleague:
> the event you're looking for is **`recording_stopped`**.

Now if your code is sensitive please do send it to our support team as a ticket. This is what my colleague meant. Now if you prefer you can post here as well. We would all be happy to assist regardless where it is sent.

I do only wish to ask to keep this only on Github or only in our tickets when it is the same subject and not in both places.

Please let us know how the **recording_stopped** event works for you in your tests.
Bane

**Comment by Hamdan85** [comment]
Understood Bane... About recording_stopped it's ok and I'll test it...

Please try to reproduce the rerecord event not beIN triggered through redo
button (after video recording finished)

**Comment by Bane-D** [comment]
Great, thank you Gabriel, looking forward to hearing how it goes :)

In regards to the _rerecord_ event - it is actually working right for all of us. We also already think we know what might be happening and if true, all you would need is to try a different browser to see if that works.

You should see the following scenario happen:
1. You record a video
2. You click on "Redo" button
3. You are shown the alert box asking you if you are sure about re-recording a video
4. If confirmed, your new event fires.

We think that you never see the alert box, however if you do, then there is another thing to look into, and I am happy to explain what, let's just see how it goes with the above steps first.
