### ISSUE TITLE
[Docs] Upload video from ZiggeoApi.videos.create(...)

### ISSUE THREAD

**Issue by lucailvec** [Ziggeo/ziggeo-client-sdk#31]
Good morning,
I'm trying to upload a video in HD to Ziggeo by using the API [https://ziggeo.com/docs/sdks/javascript/api].

I see in others issues how to use the new api of /v1/applications/*application_token*/videos as:
```javascript
const ziggeo = new window.ZiggeoApi.V2.Application({
            token: config.ZIGGEO_API_KEY,
            debug: true,
        });
ziggeo.videos.create(
            {// this are the parameter for the data_object that you mention in the docs
                file: DATA_THAT_WILL_BE_UPLOADED,
                tags: 'test_101',
                volatile: false,
            }
        ).success(
            result => {
                console.log("Result from updating: ", result);
            }
        ).error(
            error => {
                console.warn("Error from updating: ", error);
            }
        );
```
(https://ziggeo.com/docs/sdks/javascript/api)

- Which parameter for the **data_object** should i use to correctly upload an HD video ? Can you produce a working example?
- What type of vido file (in the property file ov the data_object) i have to produce for this method? A Blob? A file? A bytearray? The docs doesn't say anything.
- What is the purpose of the debug property in the costructor of the Application API? I think it doesn't work. Generally where is the docs about the costructor api of Application?

And the most important question:
- Are there any new documentation not uploaded in the website?

Best regards,
Luca

**Comment by Bane-D** [comment]
Hi Luca,

>Are there any new documentation not uploaded in the website?

We are always working on providing even more documentation and to find better ways to present them to everyone, so yes, there will be more documents released in a soon to be available update.

If you have any specifics that you are interested in seeing, please feel free to mention them to our support email (support@ziggeo.com) or forum (https://support.ziggeo.com/hc/en-us/community/topics), either of the two works and would allow us to know better what kind of info is missing or needs to be made available in different manner :)

Since I already started from last question, let me continue in the same manner:

> What is the purpose of the debug property in the costructor of the Application API? I think it doesn't work. Generally where is the docs about the costructor api of Application?

`debug:true` tells our application to capture all JavaScript console errors it can and send it to your Application (you can see that in your dashboard if there are any errors that it caught while it was turned on). This can sometimes help catch errors even if you are not the one testing it.

Now if you are using this on server side, the following might also be of use:
https://github.com/Ziggeo/ZiggeoNodeSdk/tree/master/demos

In such cases the path to media file would be enough.

When it comes to front end, you can not specify the file path and finalize it as is, rather you always need the File Object or its reference. Now since you asked for the code lets take this example:

```html
<script>
	var ziggeoApp = new ZiggeoApi.V2.Application({
		token: "APP_TOKEN"
	});

	function createVideo(file_object) {

		var createObject = {
			file: file_object,
			tags: 'test_101'
		};

		//create video
		ziggeoApp.videos.create( createObject ).success(
			function(result) {
				//object
				console.log(result);
			}
		);
	}
	
	function createInput() {
		var input_element = document.createElement('input');
		input_element.type = 'file';
		document.getElementsByTagName('body')[0].appendChild(input_element);
		input_element.addEventListener("change", function() {
			createVideo(this.files[0]);
		}, false);
	}
</script>
```
Now createInput() here is just for completeness as it allows you to see how I grab the data in this case. In general this would be some file object that you grabbed in any manner that best suits your workflow.

Now there are 2 points I would like to mention here. We can make the following two valid calls:

`createVideo("");` and `createVideo(fileObject);`

Both will make the video token be created on our server. The first one is useful if you wish to create a token at stage 1 (lets say you have multistage process) and you want to add tags and such, then at a later point you would update the same token with the actual video.
* Please note that this is not a recommended way to do it rather if in some specific case you benefit of doing it this way.

The second way is actually how our embeddings work and how you would generally want to use it and that is just as in example above, where the file is sent with the call and by the use of File Object.

Hope this helps Luca, of course feel free to ask more questions and I am happy to hear about any improvements you can suggest for our documentation and how it and us can help make the first steps much easier than they already are.
