### ISSUE TITLE
Is recordingwidth, recordingheight supported on browsers other than Chrome?

### ISSUE THREAD

**Issue by dpretty** [Ziggeo/ziggeo-client-sdk#36]
I'm trying to set the recording aspect ratio to square. The following code records at 720x720 in Chrome 80.0.3987.163, but in Firefox 75.0 the video is recorded at 1280x720.

Is it possible to control the recording aspect ratio in browsers other than Chrome?

```html
<html>
<head>
<link rel="stylesheet" href="https://assets.ziggeo.com/v2-stable/ziggeo.css" />
<script src="https://assets.ziggeo.com/v2-stable/ziggeo.js"></script>
<script>
var ziggeoApp = new ZiggeoApi.V2.Application({
	token:"xxxxxx"
});
</script></head>
<body>
<h1>TEST ZIGGEO JS</h1>


<div id="replace_me-v2_recorder"></div> <script>
    ziggeoApp.on("ready", function() {
        var recorder = new ZiggeoApi.V2.Recorder({
            element: document.getElementById("replace_me-v2_recorder"),
            attrs: {
                recordingheight: 720,
                recordingwidth: 720,
                theme: "modern",
                themecolor: "red"
            }
        });

        recorder.activate();
    });
</script>

</body>
</html>
```

**Comment by Bane-D** [comment]
Hi Dave,

That would be a yes and no kind of situation. Many browsers will now limit the amount of resolutions that you can use. If you were to specify the resolution that it does not allow you at the time to use for recording then it will just not do any recording.

Our system detects that is the case and instead finds the resolution that offers the best match to your setup.

With that said, one of my colleagues is working on implementing something that would go around this in another way which should result in what you are after.

For reference the browsers typically like and "approve of" resolutions that are seen as standards, and for others it can be available or it might not be available.

Through the use of our [video profiles](https://ziggeo.com/docs/dashboard/profiles/video-profiles/create-profile) you can get the resolution you expect every time by utilizing the frontend resolution setup and backend handling of each videos that comes in.

Hope this helps :)

**Comment by dpretty** [comment]
thanks @Bane-D 

> Our system detects that is the case and instead finds the resolution that offers the best match to your setup.

Ah ok, I can reproduce the difference between chrome and firefox with https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia  - chrome is happy to provide 720x720 but firefox raises an OverconstrainedError.

> With that said, one of my colleagues is working on implementing something that would go around this in another way which should result in what you are after.

I'd be curious to know more about this - any further info or timeline?

> Through the use of our video profiles you can get the resolution you expect every time by utilizing the frontend resolution setup and backend handling of each videos that comes in.

Can I confirm the video profiles is only available on the "Pro" pricing plan? We're currently on the $99/mo plan and I can't see any settings for video profiles in the dashboard.

Thanks.

**Comment by Bane-D** [comment]
I'll start with last first, yes that is correct Dave video profiles are only available on our Pro plan. We label them as HD feature in some areas however video profiles offer HD and SD video resolution handling.

Starter plan has a standard video profile applied of 640x480.

* You could still record in HD however your transcoded videos would always go to 640x480 or equivalent depending on original video aspect ratio.

In terms of browsers and different recording resolutions, that is true, there is still no "same in all" approach for different browser vendors and we can see that happening across all of the different browsers available. 

Now in regards to the workaround timeline. I will have to check with my colleagues about it. In general this is more of an improvement and as such requires first all kinks to be removed. Since there are some bumps in the road that are related to this to be removed that is the priority for them.

Let me try and get some approx timeframe and get back to you on it. :)

**Comment by sambua** [comment]
Hello @dpretty , could you please checkout new feature `fittodimensions` applied to revision `2.35.19` ? Should fit exact ratio you set as recordingwidth/height. Support FireFox and Chrome.
