### ISSUE TITLE
Event listeners not functioning in mobile browsers when using the Ziggeo recorder

### ISSUE THREAD

**Issue by Dinindu-Nissanka** [Ziggeo/ziggeo-client-sdk#78]
I am encountering an issue with event listeners not functioning in mobile browsers when using the Ziggeo recorder in a React project.

**Steps to Reproduce:**

1. Initialize the Ziggeo recorder in a React project using the ziggeo-client-sdk version 2.43.3.
2. Set up event listeners to observe events emitted from the Ziggeo recorder, such as the `ready_to_record` event.
3. Attempt to trigger the event on both desktop and mobile browsers.
4. Observe that the event listener works correctly on desktop browsers but not on mobile browsers.

**Expected Behavior:**

The event listener should work consistently across both desktop and mobile browsers, allowing proper observation of events emitted from the Ziggeo recorder.

**Actual Behavior:**

The event listener functions as expected in desktop browsers but fails to trigger in mobile browsers.

Environment:

- ziggeo-client-sdk version: 2.43.3
- React version: 17.0.2
- Mobile browser(s) tested: 
         - Safari - 17.4.1
         - Chrome(android) - 123.0.6312.99
         - Chrome(iOS) - 123.0.6312.52

Reproducible Code Example:

```
// Sample code used to initialize Ziggeo recorder and set up event listeners
// Please note that this is a simplified example for demonstration purposes

// Initialize Ziggeo recorder
ziggeoInstance.on('ready', () => {

    const recorderOptions = {
        width: 100,
        height: 100,
        maxheight: theme.getSpacing(136),
        skipinitial: true,
        allowupload: false,
        allowrecord: false,
        rerecordable: false,
        earlyRerecord: true,
        showplayersettingsmenu: false,
        responsive: true,
        deleteoldstreams: true,
        displaytimer: true,
        allowcustomupload: false,
        picksnapshots: false,
        theme: 'minimalist' as const,
        countdown: 3 as const,
        preventReRenderOnUpdate: true,
        timelimit: maximumTimeSeconds || 600,
        videobitrate: 2000,
        showsettings: false,
        showsettingsmenu: false,
        camerafacefront: true,
        flipCamera: true,
        localplayback: true,
        'expiration-days': expirationInDays,
        tags,
        framerate: 20,
    };

    new ZiggeoApi.V2.Recorder({
        element: recorderElement.current,
        attrs: recorderOptions,
    });
});

// useEffect hook to observe events emitted from Ziggeo client
recorder.on('ready_to_record', () => {
    // Do Something
    // The things we are doing inside this work fine in desktop browsers, but not in mobile browsers
});
```

**Comment by Bane-D** [comment]
Hi Dinindu,

Thank you for reporting the same.

I would like to mention that some browsers, especially on mobile will look to block to some extent what seems to be an ad. For example 100x100 seems too small for a video element and might be blocked to some degree if the browser decides to save battery.

That said, the events should only be available if you are using WebRTC for mobile, otherwise they will not since the native camera app will not give us the same information that we would get through JS otherwise.

`width: 100,` I would suggest to change this to `width: "100%"` which will make the player take full width and make it fluid. I would also remove the height of 100 in that case so it is not constrained in height.

`allowupload: false,` and `allowrecord: false,` will attempt to set  the recorder to not allow the upload nor recording, which is not desirable for recorder.

`responsive: true,` this is old property that is no longer in use in any way. It should not cause issues, however I would suggest removing.

I would also like to mention that the recorder has to be a variable with initialized recorder. So what you should try is to do this:
```
ziggeoInstance.on('ready', () => {
    const recorderOptions = {};

    var recorder = new ZiggeoApi.V2.Recorder({
        element: recorderElement.current,
        attrs: recorderOptions,
    });

    recorder.on('ready_to_record', () => {
        // Do Something
        // The things we are doing inside this work fine in desktop browsers, but not in mobile browsers
    });
});
```

If you want to go with more React way you could also use the following approach:
https://github.com/Ziggeo/react-ziggeo?tab=readme-ov-file#video-recorder
which will show you the way to add recorder and the events that you can listen to (and how).
